#!/bin/sh
# dgit
# Integration between git and Debian-style archives
#
# Copyright (C)2013-2021 Ian Jackson
# Copyright (C)2017-2019 Sean Whitton
# Copyright (C)2019      Matthew Vernon / Genome Research Limited
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# See update-dh-compat
# This ad-hoc script was wrtten to deal with #1002927.

set -e
perl -i -pe 's/^5$/12/' debian/compat
