#!/bin/bash
set -e
. tests/lib
. $troot/lib-baredebian

t-dependencies quilt DEBORIG

t-setup-import baredebian
t-tstunt-parsechangelog

cd $p
baredebian-test-vars
quiltmode=baredebian+git

baredebian-test-minimum

t-ok
