#!/bin/bash
set -e
. tests/lib

t-dependencies GDR

t-tstunt-parsechangelog
t-setup-import gdr-convert-gbp
t-setup-import http-git-check

cd $p

: 'non-dgit upload (but we prepare it with dgit anyway)'

v=2.0-2+nmu1
t-nmu-upload-1 nmu
gbp pq import
t-nmu-upload-2
t-some-changes $numbranch
t-nmu-upload-3

: 'done the nmu, switching back to the maintainer hat'

nmu-fold () {
	t-git-next-date
	t-dgit fetch
	t-git-next-date
	git merge --ff-only dgit/dgit/sid

	git diff --exit-code patch-queue/$nmubranch

	git branch unlaundered.$nmubranch

	t-git-debrebase
	t-gdr-good laundered

	t-git-debrebase stitch
	t-gdr-good stitched
}

nmu-fold

v=2.0-3
t-dch-commit -v $v -m "incorporate nmu"
t-dch-commit-r
t-dgit -wgf push-source

: 'now test a new upstream'

t-make-new-upstream-tarball 2.1

git checkout master
v=2.1-0+nmu1
t-nmu-upload-1 nmu2

gbp import-orig --upstream-version=2.1 --debian-branch=nmu2 ../$ust
t-dch-commit -v $v -m "new upstream $v"
gbp pq import

#t-dgit -wgf build-source

t-nmu-upload-2
t-some-changes $numbranch
t-nmu-upload-3

: 'done the nmu, back to the maintainer'

nmu-fold

t-ok
