#!/bin/bash
set -e
. tests/lib
. $troot/lib-import-chk

t-tstunt-parsechangelog
t-buildproductsdir-config

# 1.0 with diff
t-import-chk pari-extra 3-1

# 3.0 (quilt), multiple patches, multiple origs
t-import-chk example 1.0-1

# 3.0 (quilt), single-debian-patch, one orig
t-import-chk sunxi-tools 1.2-2.~~dgittest

t-ok
