#!/bin/bash
set -e
. tests/lib

t-archive pari-extra 3-1
t-git pari-extra 3-1

t-dgit clone $p

cd $p
t-cloned-fetched-good

v=3-2~dummy1
t-apply-diff 3-1 $v
debcommit -a

t-refs-same-start
t-ref-head

t-dgit --dpkg-buildpackage:-d build
t-dgit push-source

t-pushed-good dgit/sid

t-ok
