#!/bin/bash
set -e
. tests/lib

t-tstunt-parsechangelog

t-gbp-example-prep

t-dgit -wgf --quilt=gbp --dgit-view-save=split.b build-source

mkdir $tmp/empty
cd $tmp/empty
t-dgit --quilt=gbp --dgit-view-save=split.p \
	--ssh=$troot/ssh rpush-built r-build:$tmp/$p

cd $tmp/$p
t-gbp-pushed-good

t-ok
