#!/bin/bash
set -e
. tests/lib

t-dependencies sbuild man-db
t-restrict x-dgit-schroot-build

t-tstunt-parsechangelog

t-prep-newpackage example 1.1

buildrune=$(
	t-dgit-manpage 7 dgit-user | \
	perl -ne '
		next unless m/^ +Using sbuild$/ .. 0;
		next unless m/^ +\%/ .. 0;
		next if !m/\S/ .. 0;
		s/^ +\%//;
		$fixchr += s/(\s-c\s*)jessie(\s|$)/$1'"$schroot"'$2/;
		s/^\s*sbuild/$& -v/m;
		print or die $!;
		END { $fixchr == 1 or die $fixchr; }
	'
)

cd $p

build () {
	eval "$buildrune"
}

git checkout quilt-tip-1.1~0

build

git checkout gitish-only~0

cat <<'END' >clean-target-hook
#!/bin/sh
set -ex
test "$SCHROOT_SESSION_ID"
END
git add clean-target-hook
git commit -m 'insist on schroot'

build

t-ok
